
export interface Product {
    id: number;
    name: string;
    price: number;
    category: string;
    prescriptionRequired: boolean;
}

export const baseProducts: Product[] = [
  { id: 1, name: 'Ibuprofen 200mg', price: 720, category: 'Pain Relief', prescriptionRequired: false },
  { id: 2, name: 'Loratadine 10mg', price: 1000, category: 'Allergy', prescriptionRequired: false },
  { id: 9, name: 'Atorvastatin 20mg', price: 2500, category: 'Cholesterol', prescriptionRequired: true },
  { id: 3, name: 'Vitamin C 1000mg', price: 1200, category: 'Vitamins', prescriptionRequired: false },
  { id: 4, name: 'Melatonin 5mg', price: 800, category: 'Sleep Aid', prescriptionRequired: false },
  { id: 5, name: 'Omeprazole 20mg', price: 1800, category: 'Digestion', prescriptionRequired: false },
  { id: 10, name: 'Amoxicillin 500mg', price: 1500, category: 'Antibiotics', prescriptionRequired: true },
  { id: 6, name: 'Hand Sanitizer', price: 400, category: 'Personal Care', prescriptionRequired: false },
  { id: 7, name: 'Digital Thermometer', price: 1600, category: 'Devices', prescriptionRequired: false },
  { id: 8, name: 'Cough Drops (Honey)', price: 280, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 11, name: 'Paracetamol 500mg', price: 500, category: 'Pain Relief', prescriptionRequired: false },
  { id: 12, name: 'Metformin 500mg', price: 1300, category: 'Diabetes', prescriptionRequired: true },
  { id: 13, name: 'Cetirizine 10mg', price: 950, category: 'Allergy', prescriptionRequired: false },
  { id: 14, name: 'Multivitamin Gummies', price: 1500, category: 'Vitamins', prescriptionRequired: false },
  { id: 15, name: 'Lisinopril 10mg', price: 2200, category: 'Blood Pressure', prescriptionRequired: true },
  { id: 16, name: 'Antacid Tablets', price: 600, category: 'Digestion', prescriptionRequired: false },
  { id: 17, name: 'Salbutamol Inhaler', price: 2800, category: 'Asthma', prescriptionRequired: true },
  { id: 18, name: 'Band-Aid Assorted', price: 350, category: 'First Aid', prescriptionRequired: false },
  { id: 19, name: 'Aspirin 81mg', price: 450, category: 'Pain Relief', prescriptionRequired: false },
  { id: 20, name: 'Diphenhydramine 25mg', price: 550, category: 'Sleep Aid', prescriptionRequired: false },
  { id: 21, name: 'Fexofenadine 180mg', price: 1100, category: 'Allergy', prescriptionRequired: false },
  { id: 22, name: 'Vitamin D3 2000IU', price: 900, category: 'Vitamins', prescriptionRequired: false },
  { id: 23, name: 'Calcium 600mg + D3', price: 1150, category: 'Vitamins', prescriptionRequired: false },
  { id: 24, name: 'Pseudoephedrine 30mg', price: 750, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 25, name: 'Guaifenesin 400mg', price: 850, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 26, name: 'Dextromethorphan 15mg', price: 650, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 27, name: 'Loperamide 2mg', price: 500, category: 'Digestion', prescriptionRequired: false },
  { id: 28, name: 'Bismuth Subsalicylate', price: 700, category: 'Digestion', prescriptionRequired: false },
  { id: 29, name: 'Famotidine 20mg', price: 950, category: 'Digestion', prescriptionRequired: false },
  { id: 30, name: 'Simethicone 125mg', price: 600, category: 'Digestion', prescriptionRequired: false },
  { id: 31, name: 'Hydrocortisone Cream 1%', price: 550, category: 'Dermatology', prescriptionRequired: false },
  { id: 32, name: 'Clotrimazole Cream 1%', price: 750, category: 'Dermatology', prescriptionRequired: false },
  { id: 33, name: 'Miconazole Cream 2%', price: 800, category: 'Dermatology', prescriptionRequired: false },
  { id: 34, name: 'Bacitracin Ointment', price: 450, category: 'First Aid', prescriptionRequired: false },
  { id: 35, name: 'Neomycin Ointment', price: 500, category: 'First Aid', prescriptionRequired: false },
  { id: 36, name: 'Alcohol Swabs', price: 250, category: 'First Aid', prescriptionRequired: false },
  { id: 37, name: 'Gauze Pads', price: 300, category: 'First Aid', prescriptionRequired: false },
  { id: 38, name: 'Medical Tape', price: 200, category: 'First Aid', prescriptionRequired: false },
  { id: 39, name: 'Elastic Bandage', price: 400, category: 'First Aid', prescriptionRequired: false },
  { id: 40, name: 'Naproxen Sodium 220mg', price: 780, category: 'Pain Relief', prescriptionRequired: false },
  { id: 41, name: 'Sertraline 50mg', price: 1800, category: 'Mental Health', prescriptionRequired: true },
  { id: 42, name: 'Fluoxetine 20mg', price: 1700, category: 'Mental Health', prescriptionRequired: true },
  { id: 43, name: 'Escitalopram 10mg', price: 1900, category: 'Mental Health', prescriptionRequired: true },
  { id: 44, name: 'Alprazolam 0.5mg', price: 2200, category: 'Mental Health', prescriptionRequired: true },
  { id: 45, name: 'Amlodipine 5mg', price: 1400, category: 'Blood Pressure', prescriptionRequired: true },
  { id: 46, name: 'Metoprolol 50mg', price: 1550, category: 'Blood Pressure', prescriptionRequired: true },
  { id: 47, name: 'Losartan 50mg', price: 1600, category: 'Blood Pressure', prescriptionRequired: true },
  { id: 48, name: 'Hydrochlorothiazide 25mg', price: 1300, category: 'Blood Pressure', prescriptionRequired: true },
  { id: 49, name: 'Simvastatin 20mg', price: 2400, category: 'Cholesterol', prescriptionRequired: true },
  { id: 50, name: 'Rosuvastatin 10mg', price: 2600, category: 'Cholesterol', prescriptionRequired: true },
  { id: 51, name: 'Ezetimibe 10mg', price: 2700, category: 'Cholesterol', prescriptionRequired: true },
  { id: 52, name: 'Azithromycin 250mg', price: 1800, category: 'Antibiotics', prescriptionRequired: true },
  { id: 53, name: 'Ciprofloxacin 500mg', price: 1900, category: 'Antibiotics', prescriptionRequired: true },
  { id: 54, name: 'Doxycycline 100mg', price: 1600, category: 'Antibiotics', prescriptionRequired: true },
  { id: 55, name: 'Cephalexin 500mg', price: 1750, category: 'Antibiotics', prescriptionRequired: true },
  { id: 56, name: 'Glipizide 5mg', price: 1400, category: 'Diabetes', prescriptionRequired: true },
  { id: 57, name: 'Gliclazide 80mg', price: 1500, category: 'Diabetes', prescriptionRequired: true },
  { id: 58, name: 'Sitagliptin 100mg', price: 3000, category: 'Diabetes', prescriptionRequired: true },
  { id: 59, name: 'Montelukast 10mg', price: 2100, category: 'Asthma', prescriptionRequired: true },
  { id: 60, name: 'Fluticasone Propionate Nasal Spray', price: 1500, category: 'Allergy', prescriptionRequired: false },
  { id: 61, name: 'Budesonide Nasal Spray', price: 1600, category: 'Allergy', prescriptionRequired: false },
  { id: 62, name: 'Artificial Tears Eye Drops', price: 500, category: 'Eye Care', prescriptionRequired: false },
  { id: 63, name: 'Ketotifen Eye Drops', price: 800, category: 'Eye Care', prescriptionRequired: false },
  { id: 64, name: 'Carbamide Peroxide Ear Drops', price: 600, category: 'Ear Care', prescriptionRequired: false },
  { id: 65, name: 'Minoxidil 5%', price: 2500, category: 'Personal Care', prescriptionRequired: false },
  { id: 66, name: 'Finasteride 1mg', price: 2800, category: 'Men\'s Health', prescriptionRequired: true },
  { id: 67, name: 'Sildenafil 50mg', price: 3500, category: 'Men\'s Health', prescriptionRequired: true },
  { id: 68, name: 'Tadalafil 10mg', price: 4000, category: 'Men\'s Health', prescriptionRequired: true },
  { id: 69, name: 'Levonorgestrel 1.5mg', price: 1200, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 70, name: 'Miconazole Vaginal Cream', price: 900, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 71, name: 'Clotrimazole Vaginal Cream', price: 950, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 72, name: 'Prenatal Vitamins', price: 1800, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 73, name: 'Folic Acid 400mcg', price: 600, category: 'Vitamins', prescriptionRequired: false },
  { id: 74, name: 'Iron Supplement', price: 700, category: 'Vitamins', prescriptionRequired: false },
  { id: 75, name: 'Omega-3 Fish Oil 1000mg', price: 1300, category: 'Vitamins', prescriptionRequired: false },
  { id: 76, name: 'Probiotic Capsules', price: 1500, category: 'Digestion', prescriptionRequired: false },
  { id: 77, name: 'Fiber Supplement', price: 900, category: 'Digestion', prescriptionRequired: false },
  { id: 78, name: 'Docusate Sodium 100mg', price: 550, category: 'Digestion', prescriptionRequired: false },
  { id: 79, name: 'Polyethylene Glycol 3350', price: 1200, category: 'Digestion', prescriptionRequired: false },
  { id: 80, name: 'Benzoyl Peroxide 5%', price: 850, category: 'Dermatology', prescriptionRequired: false },
  { id: 81, name: 'Salicylic Acid Cleanser', price: 950, category: 'Dermatology', prescriptionRequired: false },
  { id: 82, name: 'Adapalene Gel 0.1%', price: 1800, category: 'Dermatology', prescriptionRequired: false },
  { id: 83, name: 'Sunscreen SPF 50', price: 1200, category: 'Personal Care', prescriptionRequired: false },
  { id: 84, name: 'Lip Balm with SPF', price: 300, category: 'Personal Care', prescriptionRequired: false },
  { id: 85, name: 'Moisturizing Lotion', price: 600, category: 'Personal Care', prescriptionRequired: false },
  { id: 86, name: 'Warfarin 5mg', price: 1200, category: 'Heart Health', prescriptionRequired: true },
  { id: 87, name: 'Clopidogrel 75mg', price: 2000, category: 'Heart Health', prescriptionRequired: true },
  { id: 88, name: 'Rivaroxaban 20mg', price: 4500, category: 'Heart Health', prescriptionRequired: true },
  { id: 89, name: 'Apixaban 5mg', price: 4800, category: 'Heart Health', prescriptionRequired: true },
  { id: 90, name: 'Digoxin 0.25mg', price: 1100, category: 'Heart Health', prescriptionRequired: true },
  { id: 91, name: 'Furosemide 40mg', price: 900, category: 'Blood Pressure', prescriptionRequired: true },
  { id: 92, name: 'Spironolactone 25mg', price: 1000, category: 'Blood Pressure', prescriptionRequired: true },
  { id: 93, name: 'Gabapentin 300mg', price: 1800, category: 'Neurology', prescriptionRequired: true },
  { id: 94, name: 'Pregabalin 75mg', price: 2200, category: 'Neurology', prescriptionRequired: true },
  { id: 95, name: 'Topiramate 50mg', price: 2000, category: 'Neurology', prescriptionRequired: true },
  { id: 96, name: 'Levothyroxine 50mcg', price: 1200, category: 'Endocrinology', prescriptionRequired: true },
  { id: 97, name: 'Prednisone 10mg', price: 1000, category: 'Immunology', prescriptionRequired: true },
  { id: 98, name: 'Allopurinol 100mg', price: 950, category: 'Rheumatology', prescriptionRequired: true },
  { id: 99, name: 'Tamsulosin 0.4mg', price: 1800, category: 'Men\'s Health', prescriptionRequired: true },
  { id: 100, name: 'Oxybutynin 5mg', price: 1600, category: 'Urology', prescriptionRequired: true },
  { id: 101, name: 'Clobetasol Propionate 0.05% Cream', price: 1500, category: 'Dermatology', prescriptionRequired: true },
  { id: 102, name: 'Tacrolimus 0.1% Ointment', price: 3000, category: 'Dermatology', prescriptionRequired: true },
  { id: 103, name: 'Isotretinoin 20mg', price: 3500, category: 'Dermatology', prescriptionRequired: true },
  { id: 104, name: 'Tretinoin 0.05% Cream', price: 2200, category: 'Dermatology', prescriptionRequired: true },
  { id: 105, name: 'Permethrin 5% Cream', price: 1800, category: 'Dermatology', prescriptionRequired: true },
  { id: 106, name: 'Latanoprost Eye Drops', price: 2500, category: 'Eye Care', prescriptionRequired: true },
  { id: 107, name: 'Timolol Eye Drops', price: 1500, category: 'Eye Care', prescriptionRequired: true },
  { id: 108, name: 'Dorzolamide Eye Drops', price: 1800, category: 'Eye Care', prescriptionRequired: true },
  { id: 109, name: 'Cyclosporine Eye Drops', price: 4000, category: 'Eye Care', prescriptionRequired: true },
  { id: 110, name: 'Ciprofloxacin Eye Drops', price: 1200, category: 'Eye Care', prescriptionRequired: true },
  { id: 111, name: 'Insulin Glargine', price: 3500, category: 'Diabetes', prescriptionRequired: true },
  { id: 112, name: 'Insulin Lispro', price: 3200, category: 'Diabetes', prescriptionRequired: true },
  { id: 113, name: 'Insulin Aspart', price: 3300, category: 'Diabetes', prescriptionRequired: true },
  { id: 114, name: 'Liraglutide', price: 8000, category: 'Diabetes', prescriptionRequired: true },
  { id: 115, name: 'Semaglutide', price: 9000, category: 'Diabetes', prescriptionRequired: true },
  { id: 116, name: 'Sumatriptan 50mg', price: 2500, category: 'Neurology', prescriptionRequired: true },
  { id: 117, name: 'Rizatriptan 10mg', price: 2800, category: 'Neurology', prescriptionRequired: true },
  { id: 118, name: 'Ondansetron 4mg', price: 1500, category: 'Gastroenterology', prescriptionRequired: true },
  { id: 119, name: 'Promethazine 25mg', price: 1200, category: 'Gastroenterology', prescriptionRequired: true },
  { id: 120, name: 'Meclizine 25mg', price: 800, category: 'Gastroenterology', prescriptionRequired: false },
  { id: 121, name: 'Dimenhydrinate 50mg', price: 600, category: 'Gastroenterology', prescriptionRequired: false },
  { id: 122, name: 'Orlistat 60mg', price: 2500, category: 'Weight Loss', prescriptionRequired: false },
  { id: 123, name: 'Nicotine Gum 2mg', price: 1500, category: 'Smoking Cessation', prescriptionRequired: false },
  { id: 124, name: 'Nicotine Patch', price: 2000, category: 'Smoking Cessation', prescriptionRequired: false },
  { id: 125, name: 'Bupropion 150mg', price: 2200, category: 'Smoking Cessation', prescriptionRequired: true },
  { id: 126, name: 'Varenicline 1mg', price: 4000, category: 'Smoking Cessation', prescriptionRequired: true },
  { id: 127, name: 'Tylenol 500mg', price: 550, category: 'Pain Relief', prescriptionRequired: false },
  { id: 128, name: 'Advil 200mg', price: 600, category: 'Pain Relief', prescriptionRequired: false },
  { id: 129, name: 'Aleve 220mg', price: 650, category: 'Pain Relief', prescriptionRequired: false },
  { id: 130, name: 'Benadryl 25mg', price: 450, category: 'Allergy', prescriptionRequired: false },
  { id: 131, name: 'Claritin 10mg', price: 1200, category: 'Allergy', prescriptionRequired: false },
  { id: 132, name: 'Zyrtec 10mg', price: 1250, category: 'Allergy', prescriptionRequired: false },
  { id: 133, name: 'Allegra 180mg', price: 1300, category: 'Allergy', prescriptionRequired: false },
  { id: 134, name: 'Mucinex 600mg', price: 1400, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 135, name: 'Robitussin DM', price: 900, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 136, name: 'Sudafed PE', price: 850, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 137, name: 'NyQuil Cold & Flu', price: 1100, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 138, name: 'DayQuil Cold & Flu', price: 1100, category: 'Cold & Flu', prescriptionRequired: false },
  { id: 139, name: 'Pepto-Bismol', price: 650, category: 'Digestion', prescriptionRequired: false },
  { id: 140, name: 'Imodium A-D', price: 700, category: 'Digestion', prescriptionRequired: false },
  { id: 141, name: 'Tums Antacid', price: 450, category: 'Digestion', prescriptionRequired: false },
  { id: 142, name: 'Gas-X', price: 550, category: 'Digestion', prescriptionRequired: false },
  { id: 143, name: 'MiraLAX', price: 1300, category: 'Digestion', prescriptionRequired: false },
  { id: 144, name: 'Dulcolax', price: 750, category: 'Digestion', prescriptionRequired: false },
  { id: 145, name: 'Colace', price: 800, category: 'Digestion', prescriptionRequired: false },
  { id: 146, name: 'Preparation H', price: 900, category: 'Digestion', prescriptionRequired: false },
  { id: 147, name: 'Cortizone-10', price: 600, category: 'Dermatology', prescriptionRequired: false },
  { id: 148, name: 'Neosporin', price: 700, category: 'First Aid', prescriptionRequired: false },
  { id: 149, name: 'Lotrimin AF', price: 950, category: 'Dermatology', prescriptionRequired: false },
  { id: 150, name: 'Lamisil AT', price: 1100, category: 'Dermatology', prescriptionRequired: false },
  { id: 151, name: 'Unisom SleepTabs', price: 750, category: 'Sleep Aid', prescriptionRequired: false },
  { id: 152, name: 'ZzzQuil', price: 850, category: 'Sleep Aid', prescriptionRequired: false },
  { id: 153, name: 'Dramamine', price: 550, category: 'Gastroenterology', prescriptionRequired: false },
  { id: 154, name: 'Bonine', price: 600, category: 'Gastroenterology', prescriptionRequired: false },
  { id: 155, name: 'Visine Eye Drops', price: 450, category: 'Eye Care', prescriptionRequired: false },
  { id: 156, name: 'Bausch + Lomb Soothe', price: 900, category: 'Eye Care', prescriptionRequired: false },
  { id: 157, name: 'Systane Ultra', price: 1000, category: 'Eye Care', prescriptionRequired: false },
  { id: 158, name: 'Refresh Tears', price: 950, category: 'Eye Care', prescriptionRequired: false },
  { id: 159, name: 'Debrox Earwax Removal', price: 700, category: 'Ear Care', prescriptionRequired: false },
  { id: 160, name: 'Rogaine Foam', price: 3000, category: 'Personal Care', prescriptionRequired: false },
  { id: 161, name: 'Nizoral A-D Shampoo', price: 1500, category: 'Dermatology', prescriptionRequired: false },
  { id: 162, name: 'Selsun Blue Shampoo', price: 1000, category: 'Dermatology', prescriptionRequired: false },
  { id: 163, name: 'Head & Shoulders Shampoo', price: 800, category: 'Personal Care', prescriptionRequired: false },
  { id: 164, name: 'CoQ10 100mg', price: 2000, category: 'Vitamins', prescriptionRequired: false },
  { id: 165, name: 'Turmeric Curcumin', price: 1800, category: 'Vitamins', prescriptionRequired: false },
  { id: 166, name: 'Glucosamine Chondroitin', price: 2200, category: 'Vitamins', prescriptionRequired: false },
  { id: 167, name: 'Magnesium 250mg', price: 900, category: 'Vitamins', prescriptionRequired: false },
  { id: 168, name: 'Zinc 50mg', price: 700, category: 'Vitamins', prescriptionRequired: false },
  { id: 169, name: 'Vitamin B12 1000mcg', price: 850, category: 'Vitamins', prescriptionRequired: false },
  { id: 170, name: 'Biotin 5000mcg', price: 1100, category: 'Vitamins', prescriptionRequired: false },
  { id: 171, name: 'Crest 3D Whitestrips', price: 3500, category: 'Personal Care', prescriptionRequired: false },
  { id: 172, name: 'Listerine Antiseptic Mouthwash', price: 700, category: 'Personal Care', prescriptionRequired: false },
  { id: 173, name: 'Sensodyne Toothpaste', price: 500, category: 'Personal Care', prescriptionRequired: false },
  { id: 174, name: 'Colgate Total Toothpaste', price: 400, category: 'Personal Care', prescriptionRequired: false },
  { id: 175, name: 'Oral-B Electric Toothbrush', price: 5000, category: 'Devices', prescriptionRequired: false },
  { id: 176, name: 'Waterpik Water Flosser', price: 6000, category: 'Devices', prescriptionRequired: false },
  { id: 177, name: 'Omron Blood Pressure Monitor', price: 4500, category: 'Devices', prescriptionRequired: false },
  { id: 178, name: 'Accu-Chek Glucose Meter', price: 2500, category: 'Devices', prescriptionRequired: false },
  { id: 179, name: 'Pulse Oximeter', price: 2000, category: 'Devices', prescriptionRequired: false },
  { id: 180, name: 'Nebulizer Machine', price: 5500, category: 'Devices', prescriptionRequired: false },
  { id: 181, name: 'Metamucil Fiber Supplement', price: 1500, category: 'Digestion', prescriptionRequired: false },
  { id: 182, name: 'Citrucel Fiber Supplement', price: 1400, category: 'Digestion', prescriptionRequired: false },
  { id: 183, name: 'Benefiber', price: 1600, category: 'Digestion', prescriptionRequired: false },
  { id: 184, name: 'Align Probiotic', price: 2800, category: 'Digestion', prescriptionRequired: false },
  { id: 185, name: 'Culturelle Probiotic', category: 'Digestion', prescriptionRequired: false, price: 2500 },
  { id: 186, name: 'Florastor Probiotic', price: 2900, category: 'Digestion', prescriptionRequired: false },
  { id: 187, name: 'Ensure Nutrition Shake', price: 1200, category: 'Nutrition', prescriptionRequired: false },
  { id: 188, name: 'Boost Nutrition Shake', price: 1100, category: 'Nutrition', prescriptionRequired: false },
  { id: 189, name: 'Glucerna Diabetes Shake', price: 1500, category: 'Nutrition', prescriptionRequired: false },
  { id: 190, name: 'Pedialyte Electrolyte Solution', price: 800, category: 'Nutrition', prescriptionRequired: false },
  { id: 191, name: 'Gatorade Thirst Quencher', price: 200, category: 'Nutrition', prescriptionRequired: false },
  { id: 192, name: 'Clif Bar', price: 150, category: 'Nutrition', prescriptionRequired: false },
  { id: 193, name: 'Kind Bar', price: 180, category: 'Nutrition', prescriptionRequired: false },
  { id: 194, name: 'Voltaren Arthritis Pain Gel', price: 1800, category: 'Pain Relief', prescriptionRequired: false },
  { id: 195, name: 'Aspercreme with Lidocaine', price: 1200, category: 'Pain Relief', prescriptionRequired: false },
  { id: 196, name: 'Icy Hot Pain Relieving Cream', price: 900, category: 'Pain Relief', prescriptionRequired: false },
  { id: 197, name: 'Biofreeze Pain Relief Gel', price: 1000, category: 'Pain Relief', prescriptionRequired: false },
  { id: 198, name: 'Tiger Balm Pain Relieving Ointment', price: 800, category: 'Pain Relief', prescriptionRequired: false },
  { id: 199, name: 'Abreva Cold Sore Treatment', price: 1800, category: 'Dermatology', prescriptionRequired: false },
  { id: 200, name: 'Compound W Wart Remover', price: 1200, category: 'Dermatology', prescriptionRequired: false },
  { id: 201, name: 'Dr. Scholl\'s Corn Removers', price: 800, category: 'Personal Care', prescriptionRequired: false },
  { id: 202, name: 'Tinactin Antifungal Cream', price: 900, category: 'Dermatology', prescriptionRequired: false },
  { id: 203, name: 'Monistat 7', price: 1600, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 204, name: 'Vagisil Medicated Creme', price: 1000, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 205, name: 'E.P.T. Pregnancy Test', price: 1500, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 206, name: 'First Response Pregnancy Test', price: 1800, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 207, name: 'Clearblue Digital Pregnancy Test', price: 2200, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 208, name: 'Trojan Condoms', price: 800, category: 'Personal Care', prescriptionRequired: false },
  { id: 209, name: 'Durex Condoms', price: 750, category: 'Personal Care', prescriptionRequired: false },
  { id: 210, name: 'KY Jelly Lubricant', price: 600, category: 'Personal Care', prescriptionRequired: false },
  { id: 211, name: 'Plan B One-Step', price: 4000, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 212, name: 'Aftera', price: 3500, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 213, name: 'Azo Urinary Pain Relief', price: 1000, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 214, name: 'Cranberry Pills', price: 1200, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 215, name: 'Midol Complete', price: 900, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 216, name: 'Pamprin Multi-Symptom', price: 850, category: 'Women\'s Health', prescriptionRequired: false },
  { id: 217, name: 'Flonase Allergy Relief', price: 1700, category: 'Allergy', prescriptionRequired: false },
  { id: 218, name: 'Nasacort Allergy 24HR', price: 1600, category: 'Allergy', prescriptionRequired: false }
];


export const healthKits = [
    { 
        name: 'First-Aid Kit',
        description: 'Essentials for handling minor cuts and scrapes.',
        items: ['Band-Aid Assorted', 'Hand Sanitizer', 'Ibuprofen 200mg']
    },
    { 
        name: 'Cold & Flu Care Package',
        description: 'Everything you need to fight off a common cold.',
        items: ['Paracetamol 500mg', 'Cough Drops (Honey)', 'Vitamin C 1000mg', 'Digital Thermometer']
    }
];

    